import test from 'node:test';
import assert from 'node:assert/strict';
import {runtime} from './receipt-scan-harness.mjs';
const root='artifacts/berman-app/public/data/';
function setup(){
 const p=runtime();
 p.context.redPaper={id:'paper_123',captureId:'cap-local',kind:'delivery',state:'accepted',number:'123',docDay:'2026-10-08',rev:1,rows:[{itemCode:'101',qty:9}]};
 p.run(`receiptDraftId='receipt-red';receiptOpened=true;receiptList=structuredClone(testData.items);aiScanResponse={perDocument:[{paperId:'paper_123'}]};paperLocalSave({'cap-local':{captureId:'cap-local',paper:redPaper,scan:{paidResult:true}}});saveReceiptDraft();`);
 const dbroot=p.run("dataPath('papers','paper_123').slice(0,-2).join('/')+'/'");
 return {...p,dbroot,save:()=>p.run("finishSharedReceipt('receipt-red',{items:[{qty:9}],paperDocs:[{paperId:'paper_123'}]})")};
}
test('staged receiving delivery never writes during intermediate flush',async()=>{const p=setup();await p.run('paperFlushPending()');assert.equal(p.finalCloud.get(p.dbroot+'papers/paper_123'),null);});
test('cached identical delivery remotely tombstoned must block finalization',async()=>{const p=setup();p.run('papers=[structuredClone(redPaper)]');p.finalCloud.put(p.dbroot+'papers/paper_123',{...p.context.redPaper,deleted:true,state:'void'});assert.equal(await p.save(),false);assert.equal(p.finalCloud.get(p.dbroot+'receipts/receipt-red'),null);assert.equal(p.run("Boolean(paperLocalResults()['cap-local'].ackedAt)"),false);});
test('cached identical delivery remotely changed must block finalization',async()=>{const p=setup();p.run('papers=[structuredClone(redPaper)]');p.finalCloud.put(p.dbroot+'papers/paper_123',{...p.context.redPaper,rows:[{itemCode:'101',qty:17}]});assert.equal(await p.save(),false);assert.equal(p.finalCloud.get(p.dbroot+'receipts/receipt-red'),null);});
test('same fingerprint existing capture is preserved when finalizing duplicate photo',async()=>{const p=setup();const remote={...p.context.redPaper,captureId:'cap-original',rev:2};p.context.redRemote=remote;p.run('papers=[structuredClone(redRemote)]');p.finalCloud.put(p.dbroot+'papers/paper_123',remote);assert.equal(await p.save(),true);assert.equal(p.finalCloud.get(p.dbroot+'papers/paper_123').captureId,'cap-original');});
test('remote conflicting delivery cannot be replaced by new local capture',async()=>{const p=setup();const remote={...p.context.redPaper,captureId:'cap-original',rows:[{itemCode:'101',qty:17}]};p.context.redRemote=remote;p.run('papers=[structuredClone(redRemote)]');p.finalCloud.put(p.dbroot+'papers/paper_123',remote);assert.equal(await p.save(),false);assert.equal(p.finalCloud.get(p.dbroot+'papers/paper_123').captureId,'cap-original');assert.equal(p.finalCloud.get(p.dbroot+'papers/paper_123').rows[0].qty,17);});
test('remote deletion tombstone same capture cannot resurrect',async()=>{const p=setup();const remote={...p.context.redPaper,deleted:true,state:'void'};p.context.redRemote=remote;p.run('papers=[structuredClone(redRemote)]');p.finalCloud.put(p.dbroot+'papers/paper_123',remote);assert.equal(await p.save(),false);assert.equal(p.finalCloud.get(p.dbroot+'papers/paper_123').deleted,true);});
test('first final save stores receipt delivery and scan together',async()=>{const p=setup();assert.equal(await p.save(),true);assert.ok(p.finalCloud.get(p.dbroot+'receipts/receipt-red'));assert.ok(p.finalCloud.get(p.dbroot+'papers/paper_123'));assert.ok(p.finalCloud.get(p.dbroot+'paperScans/paper_123'));assert.equal(p.run("Boolean(paperLocalResults()['cap-local'].ackedAt)"),true);});
test('delivery paper edited during final commit prevents clearing its receiving session',async()=>{const p=setup();let release;p.finalCloud.commitGate=new Promise(r=>release=r);const pending=p.save();await new Promise(r=>setTimeout(r,5));p.run("paperPatchLocal('cap-local',cur=>({...cur,paper:{...cur.paper,rev:2,rows:[{itemCode:'101',qty:17}]}}))");release();assert.equal(await pending,false);assert.equal(p.run("paperLocalResults()['cap-local'].paper.rows[0].qty"),17);assert.equal(p.run("Boolean(paperLocalResults()['cap-local'].ackedAt)"),false);});
